# Generated by Django 5.2.9 on 2025-12-12 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('interpretation', models.TextField()),
                ('source', models.CharField(choices=[('dreammoods', 'DreamMoods')], default='dreammoods', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['keyword'],
                'indexes': [models.Index(fields=['keyword'], name='api_dreamsy_keyword_9c9ff7_idx'), models.Index(fields=['source'], name='api_dreamsy_source_3c81a1_idx')],
            },
        ),
    ]
