# Generated by Django 5.2.9 on 2025-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dreamsymbol'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dreamsymbol',
            name='api_dreamsy_keyword_9c9ff7_idx',
        ),
        migrations.AlterField(
            model_name='dreamsymbol',
            name='keyword',
            field=models.TextField(),
        ),
    ]
