# Generated by Django 5.2.9 on 2025-12-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_tokenusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.URLField(blank=True, help_text='Profile picture URL from OAuth provider', null=True),
        ),
    ]
