# Generated by Django 5.2.9 on 2025-12-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.URLField(blank=True, help_text='Profile picture URL from OAuth provider', max_length=2048, null=True),
        ),
    ]
