# Generated by Django 5.2.9 on 2025-12-31 14:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_trial_ends_at_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HijackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(help_text='When this hijack session expires')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(help_text='The superadmin who initiated the hijack', on_delete=django.db.models.deletion.CASCADE, related_name='hijack_sessions_as_admin', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='The user being viewed', on_delete=django.db.models.deletion.CASCADE, related_name='hijack_sessions_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_token', 'is_active'], name='api_hijacks_session_0107ec_idx'), models.Index(fields=['admin_user', 'is_active'], name='api_hijacks_admin_u_704c82_idx')],
            },
        ),
    ]
