# Generated by Django 5.2.9 on 2026-01-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_hijacksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_frequency',
            field=models.CharField(choices=[('off', 'Off - No emails'), ('daily', 'Daily'), ('every_2_days', 'Every 2 days'), ('every_3_days', 'Every 3 days'), ('every_5_days', 'Every 5 days'), ('weekly', 'Weekly')], default='daily', help_text='How often to receive daily insight emails', max_length=20),
        ),
    ]
