# Generated by Django 5.2.9 on 2026-01-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userprofile_email_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicdreamsubmission',
            name='email_subscribed',
            field=models.BooleanField(default=True, help_text='Whether user is subscribed to follow-up emails'),
        ),
        migrations.AddField(
            model_name='publicdreamsubmission',
            name='last_insight_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last follow-up insight email was sent', null=True),
        ),
        migrations.AddField(
            model_name='publicdreamsubmission',
            name='unsubscribe_token',
            field=models.UUIDField(blank=True, editable=False, help_text='Unique token for unsubscribe link', null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='publicdreamsubmission',
            index=models.Index(fields=['unsubscribe_token'], name='api_publicd_unsubsc_7b166f_idx'),
        ),
        migrations.AddIndex(
            model_name='publicdreamsubmission',
            index=models.Index(fields=['email_subscribed'], name='api_publicd_email_s_110717_idx'),
        ),
    ]
