# Generated by Django 5.2.9 on 2026-01-04 13:06

from django.db import migrations
import uuid


def populate_unsubscribe_tokens(apps, schema_editor):
    """Populate unsubscribe_token for existing PublicDreamSubmission records"""
    PublicDreamSubmission = apps.get_model('api', 'PublicDreamSubmission')
    for submission in PublicDreamSubmission.objects.filter(unsubscribe_token__isnull=True):
        submission.unsubscribe_token = uuid.uuid4()
        submission.save(update_fields=['unsubscribe_token'])


def reverse_populate_tokens(apps, schema_editor):
    """Reverse operation - set tokens to null"""
    PublicDreamSubmission = apps.get_model('api', 'PublicDreamSubmission')
    PublicDreamSubmission.objects.all().update(unsubscribe_token=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_publicdreamsubmission_email_subscribed_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_unsubscribe_tokens, reverse_populate_tokens),
    ]
