# Generated by Django 5.2.9 on 2026-01-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_populate_unsubscribe_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicdreamsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
