# Generated by Django 5.2.9 on 2026-01-01 15:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('subject_template', models.CharField(max_length=255)),
                ('html_template', models.TextField()),
                ('text_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(help_text='Email template used', max_length=255)),
                ('context_data', models.JSONField(default=dict, help_text='Template context data')),
                ('email_type', models.CharField(choices=[('transactional', 'Transactional'), ('reflection', 'Reflection'), ('marketing', 'Marketing'), ('system', 'System')], db_index=True, default='transactional', max_length=20)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Custom reply-to address (for reflections)', max_length=254, null=True)),
                ('from_email', models.EmailField(help_text='Sender email address', max_length=254)),
                ('provider_name', models.CharField(default='postmark', help_text='Email provider used', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, help_text="Provider's message ID", max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Associated user (if registered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('open', 'Opened'), ('click', 'Clicked'), ('bounce', 'Bounced'), ('spam', 'Marked as Spam'), ('unsubscribe', 'Unsubscribed'), ('reply', 'Replied')], db_index=True, max_length=20)),
                ('event_data', models.JSONField(default=dict, help_text='Raw event data from provider')),
                ('clicked_url', models.URLField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='emails.email')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sender_email', models.EmailField(db_index=True, max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('text_content', models.TextField(help_text='Plain text body')),
                ('html_content', models.TextField(blank=True, help_text='HTML body')),
                ('recipient_email', models.EmailField(help_text='Which of our emails it was sent to', max_length=254)),
                ('headers', models.JSONField(default=dict, help_text='Email headers')),
                ('raw_data', models.JSONField(default=dict, help_text='Raw webhook data')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_email', models.ForeignKey(blank=True, help_text='Original email this is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='emails.email')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'email_type', 'created_at'], name='emails_emai_user_id_c0a653_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['recipient_email', 'created_at'], name='emails_emai_recipie_d27336_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['status', 'created_at'], name='emails_emai_status_8eae4a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['email', 'event_type'], name='emails_emai_email_i_2914a1_idx'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['event_type', 'created_at'], name='emails_emai_event_t_ddc320_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['sender_email', 'received_at'], name='emails_inbo_sender__620df8_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['processed', 'received_at'], name='emails_inbo_process_29fa83_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['original_email', 'received_at'], name='emails_inbo_origina_27be9b_idx'),
        ),
    ]
