# Generated by Django 5.2.9 on 2026-01-04 14:27

from django.db import migrations, models


def migrate_email_types(apps, schema_editor):
    """
    Migrate old email types to new email types:
    - 'transactional' -> 'public-interpretation' (for public dream interpretations)
    - 'reflection' -> 'appuser-followup' (for app user reflections)
    - 'daily_insight' -> 'appuser-followup' (for app user daily insights)
    - 'marketing' -> 'public-followup' (or delete if unused)
    - 'system' -> 'public-interpretation' (or delete if unused)
    """
    Email = apps.get_model('emails', 'Email')

    # Map old types to new types
    Email.objects.filter(email_type='transactional').update(email_type='public-interpretation')
    Email.objects.filter(email_type='reflection').update(email_type='appuser-followup')
    Email.objects.filter(email_type='daily_insight').update(email_type='appuser-followup')
    Email.objects.filter(email_type='marketing').update(email_type='public-followup')
    Email.objects.filter(email_type='system').update(email_type='public-interpretation')


def reverse_migrate_email_types(apps, schema_editor):
    """
    Reverse migration - best effort to restore old email types
    """
    Email = apps.get_model('emails', 'Email')

    # This is best-effort since we lose information
    Email.objects.filter(email_type='public-interpretation').update(email_type='transactional')
    Email.objects.filter(email_type='public-followup').update(email_type='marketing')
    Email.objects.filter(email_type='appuser-followup').update(email_type='reflection')


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        # First, increase the max_length to accommodate longer values during migration
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.CharField(choices=[('transactional', 'Transactional'), ('reflection', 'Reflection'), ('daily_insight', 'Daily Insight'), ('marketing', 'Marketing'), ('system', 'System'), ('public-interpretation', 'Public Interpretation'), ('public-followup', 'Public Follow-up'), ('appuser-followup', 'App User Follow-up')], db_index=True, default='transactional', max_length=30),
        ),
        # Then migrate the data
        migrations.RunPython(migrate_email_types, reverse_migrate_email_types),
        # Finally, update to the new choices only
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.CharField(choices=[('public-interpretation', 'Public Interpretation'), ('public-followup', 'Public Follow-up'), ('appuser-followup', 'App User Follow-up')], db_index=True, default='public-interpretation', max_length=30),
        ),
    ]
