# Generated by Django 5.2.9 on 2026-01-01 15:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0012_hijacksession'),
        ('emails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reflection_type', models.CharField(choices=[('followup_3day', '3-Day Follow-up'), ('followup_7day', '7-Day Follow-up'), ('followup_14day', '14-Day Follow-up'), ('pattern_insight', 'Pattern Insight'), ('symbol_evolution', 'Symbol Evolution'), ('anniversary', 'Dream Anniversary')], db_index=True, max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='AI-generated reflection content')),
                ('reply_to_email', models.EmailField(help_text='Unique reply-to address for tracking responses', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dream_conversation', models.ForeignKey(help_text='The original dream conversation this reflection is about', on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='api.conversation')),
                ('email', models.OneToOneField(blank=True, help_text='Link to the actual email sent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflection', to='emails.email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReflectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('raw_content', models.TextField(help_text='Raw email reply content')),
                ('cleaned_content', models.TextField(help_text='Cleaned/parsed reply content')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dream_brain.reflection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SubconsciousInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('insight_type', models.CharField(choices=[('symbol_meaning', 'Symbol Personal Meaning'), ('emotional_pattern', 'Emotional Pattern'), ('trigger', 'Dream Trigger'), ('resolution_pattern', 'Resolution Pattern'), ('recurring_theme', 'Recurring Theme'), ('relationship_dynamic', 'Relationship Dynamic')], db_index=True, max_length=30)),
                ('content', models.TextField(help_text='The actual insight content')),
                ('dream_symbols', models.JSONField(default=list, help_text='Related dream symbols')),
                ('emotional_valence', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], default='neutral', max_length=20)),
                ('confidence', models.FloatField(default=0.5, help_text='AI confidence in this insight (0-1)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_response', models.ForeignKey(help_text='The response this insight was extracted from', on_delete=django.db.models.deletion.CASCADE, related_name='extracted_insights', to='dream_brain.reflectionresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subconscious_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('symbol', models.CharField(db_index=True, help_text="The symbol (e.g., 'water', 'falling')", max_length=255)),
                ('personal_meaning', models.TextField(help_text='What this symbol means to THIS user')),
                ('standard_meaning', models.TextField(blank=True, help_text='Standard dream interpretation meaning')),
                ('divergence_notes', models.TextField(blank=True, help_text='How the personal meaning differs from standard')),
                ('appearance_count', models.IntegerField(default=1, help_text='How many times this symbol has appeared')),
                ('last_appeared', models.DateTimeField(help_text='When this symbol last appeared in a dream')),
                ('confidence_score', models.FloatField(default=0.5, help_text='Confidence in this personal meaning (0-1)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_symbols', to=settings.AUTH_USER_MODEL)),
                ('related_insights', models.ManyToManyField(blank=True, related_name='personal_symbols', to='dream_brain.subconsciousinsight')),
            ],
            options={
                'ordering': ['-appearance_count', '-last_appeared'],
            },
        ),
        migrations.CreateModel(
            name='DreamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('pattern_type', models.CharField(choices=[('temporal', 'Temporal Pattern'), ('emotional', 'Emotional Pattern'), ('situational', 'Situational Pattern'), ('symbolic', 'Symbolic Pattern')], db_index=True, max_length=30)),
                ('title', models.CharField(help_text='Short title for the pattern', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the pattern')),
                ('evidence', models.JSONField(default=dict, help_text='Supporting evidence/data for this pattern')),
                ('occurrence_count', models.IntegerField(default=1, help_text='How many times this pattern has been observed')),
                ('confidence_score', models.FloatField(default=0.5, help_text='Confidence in this pattern (0-1)')),
                ('last_observed', models.DateTimeField(help_text='When this pattern was last observed')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Whether we're still tracking this pattern")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurrence_count', '-last_observed'],
                'indexes': [models.Index(fields=['user', 'pattern_type', 'is_active'], name='dream_brain_user_id_315880_idx'), models.Index(fields=['user', 'occurrence_count'], name='dream_brain_user_id_22bc9f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['user', 'reflection_type', 'created_at'], name='dream_brain_user_id_9b9f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['dream_conversation', 'created_at'], name='dream_brain_dream_c_524481_idx'),
        ),
        migrations.AddIndex(
            model_name='reflection',
            index=models.Index(fields=['status', 'created_at'], name='dream_brain_status_098b53_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectionresponse',
            index=models.Index(fields=['user', 'processed', 'received_at'], name='dream_brain_user_id_80353c_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectionresponse',
            index=models.Index(fields=['reflection', 'received_at'], name='dream_brain_reflect_5ea3a2_idx'),
        ),
        migrations.AddIndex(
            model_name='subconsciousinsight',
            index=models.Index(fields=['user', 'insight_type', 'created_at'], name='dream_brain_user_id_aaebcb_idx'),
        ),
        migrations.AddIndex(
            model_name='subconsciousinsight',
            index=models.Index(fields=['confidence'], name='dream_brain_confide_91a7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='personalsymbol',
            index=models.Index(fields=['user', 'symbol'], name='dream_brain_user_id_052c39_idx'),
        ),
        migrations.AddIndex(
            model_name='personalsymbol',
            index=models.Index(fields=['user', 'appearance_count'], name='dream_brain_user_id_9c7bd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personalsymbol',
            unique_together={('user', 'symbol')},
        ),
    ]
