# Generated by Django 5.2.9 on 2026-01-02 13:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_hijacksession'),
        ('dream_brain', '0002_dailyinsight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInsightResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('raw_content', models.TextField(help_text='Raw email reply content')),
                ('cleaned_content', models.TextField(help_text='Cleaned/parsed reply content')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('daily_insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dream_brain.dailyinsight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_insight_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['user', 'processed', 'received_at'], name='dream_brain_user_id_94dc28_idx'), models.Index(fields=['daily_insight', 'received_at'], name='dream_brain_daily_i_07e6bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('dream', 'Dream'), ('chat_summary', 'Chat Summary'), ('email_response_summary', 'Email Response Summary')], db_index=True, max_length=30)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this event occurred')),
                ('data', models.JSONField(default=dict, help_text="Concise structured info. E.g., {'dream_text': '...', 'themes': [...]} or {'summary': '...', 'key_points': [...]}")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dream', models.ForeignKey(blank=True, help_text='Optional: link to the dream conversation this event is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='api.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['user', '-at'], name='dream_brain_user_id_964e82_idx'), models.Index(fields=['user', 'kind', '-at'], name='dream_brain_user_id_2873e0_idx'), models.Index(fields=['dream', '-at'], name='dream_brain_dream_i_13877e_idx')],
            },
        ),
    ]
