# Generated by Django 5.2.9 on 2026-01-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_brain', '0003_dailyinsightresponse_timelineevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalsymbol',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='personalsymbol',
            name='related_insights',
        ),
        migrations.RemoveField(
            model_name='personalsymbol',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='dream_conversation',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reflectionresponse',
            name='reflection',
        ),
        migrations.RemoveField(
            model_name='reflectionresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subconsciousinsight',
            name='source_response',
        ),
        migrations.RemoveField(
            model_name='subconsciousinsight',
            name='user',
        ),
        migrations.DeleteModel(
            name='DreamPattern',
        ),
        migrations.DeleteModel(
            name='PersonalSymbol',
        ),
        migrations.DeleteModel(
            name='Reflection',
        ),
        migrations.DeleteModel(
            name='ReflectionResponse',
        ),
        migrations.DeleteModel(
            name='SubconsciousInsight',
        ),
    ]
